use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=shaders/ui.vert");
    println!("cargo:rerun-if-changed=shaders/ui.frag");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let mut generated = String::from("// generated by build.rs; do not edit\n");
    for (name, source) in [
        ("UI_VERTEX_SPIRV", "shaders/ui.vert"),
        ("UI_FRAGMENT_SPIRV", "shaders/ui.frag"),
    ] {
        let output = out_dir.join(format!("{name}.spv"));
        let compiled = Command::new("glslc")
            .args([source, "-o"])
            .arg(&output)
            .status()
            .map(|status| status.success())
            .unwrap_or(false);
        let words = if compiled {
            fs::read(&output)
                .ok()
                .filter(|bytes| bytes.len() >= 4 && bytes.len() % 4 == 0)
                .map(|bytes| {
                    bytes
                        .chunks_exact(4)
                        .map(|word| u32::from_le_bytes([word[0], word[1], word[2], word[3]]))
                        .collect::<Vec<_>>()
                })
                .unwrap_or_default()
        } else {
            Vec::new()
        };
        generated.push_str(&format!("pub static {name}: &[u32] = &["));
        for word in words {
            generated.push_str(&format!("0x{word:08x},"));
        }
        generated.push_str("];\n");
    }
    fs::write(out_dir.join("ui_shaders.rs"), generated).expect("write generated shader module");
}
