use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=native/src/batch_transform.c");
    println!("cargo:rerun-if-changed=native/include/rke_native.h");
    if env::var_os("CARGO_FEATURE_NATIVE_ACCEL").is_some()
        && env::var_os("CARGO_CFG_UNIX").is_some()
    {
        compile_native_accel();
    }
    println!("cargo:rerun-if-changed=shaders/ui.vert");
    println!("cargo:rerun-if-changed=shaders/ui.frag");
    println!("cargo:rerun-if-changed=shaders/world.vert");
    println!("cargo:rerun-if-changed=shaders/world.frag");
    println!("cargo:rerun-if-changed=shaders/culling/frustum_cull.comp");
    println!("cargo:rerun-if-changed=shaders/culling/build_indirect.comp");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let mut generated = String::from("// generated by build.rs; do not edit\n");
    for (name, source) in [
        ("UI_VERTEX_SPIRV", "shaders/ui.vert"),
        ("UI_FRAGMENT_SPIRV", "shaders/ui.frag"),
        ("WORLD_VERTEX_SPIRV", "shaders/world.vert"),
        ("WORLD_FRAGMENT_SPIRV", "shaders/world.frag"),
        ("FRUSTUM_CULL_SPIRV", "shaders/culling/frustum_cull.comp"),
        (
            "BUILD_INDIRECT_SPIRV",
            "shaders/culling/build_indirect.comp",
        ),
    ] {
        let output = out_dir.join(format!("{name}.spv"));
        let compiled = Command::new("glslc")
            .args([source, "-o"])
            .arg(&output)
            .status()
            .map(|status| status.success())
            .unwrap_or(false);
        let require_glslc = env::var_os("RKE_REQUIRE_GLSLC").is_some();
        if require_glslc && !compiled {
            panic!("failed to compile {source}; glslc is required when RKE_REQUIRE_GLSLC is set");
        }
        let words = if compiled {
            fs::read(&output)
                .ok()
                .filter(|bytes| bytes.len() >= 4 && bytes.len() % 4 == 0)
                .map(|bytes| {
                    bytes
                        .as_chunks::<4>()
                        .0
                        .iter()
                        .map(|word| u32::from_le_bytes([word[0], word[1], word[2], word[3]]))
                        .collect::<Vec<_>>()
                })
                .unwrap_or_default()
        } else {
            println!("cargo:warning={source} was not compiled; generated shader bytes are empty");
            Vec::new()
        };
        generated.push_str(&format!("pub static {name}: &[u32] = &["));
        for word in words {
            generated.push_str(&format!("0x{word:08x},"));
        }
        generated.push_str("];\n");
    }
    fs::write(out_dir.join("ui_shaders.rs"), generated).expect("write generated shader module");
}

fn compile_native_accel() {
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let object = out_dir.join("rke_batch_transform.o");
    let archive = out_dir.join("librke_native.a");
    let compiler = env::var("CC").unwrap_or_else(|_| "cc".to_owned());
    let status = Command::new(compiler)
        .args([
            "-O3",
            "-fPIC",
            "-std=c11",
            "-I",
            "native/include",
            "-c",
            "native/src/batch_transform.c",
            "-o",
        ])
        .arg(&object)
        .status()
        .expect("failed to invoke C compiler for native-accel");
    assert!(status.success(), "native-accel C compilation failed");
    let status = Command::new("ar")
        .args(["crus"])
        .arg(&archive)
        .arg(&object)
        .status()
        .expect("failed to invoke ar for native-accel");
    assert!(status.success(), "native-accel archive creation failed");
    println!("cargo:rustc-link-search=native={}", out_dir.display());
    println!("cargo:rustc-link-lib=static=rke_native");
    println!("cargo:rustc-link-lib=m");
}
