name: coverage

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  llvm-cov:
    name: LLVM coverage report
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87
      - uses: Swatinem/rust-cache@49a0bdc70d2e1b713ca9e2869b211fcce03d3c1c
      - uses: taiki-e/install-action@9983c65e42da123ff25d1f78505eb6de315aa172
        with:
          tool: cargo-llvm-cov
      - run: cargo llvm-cov --all-features --lib --tests --lcov --output-path lcov.info -- --test-threads=1
      - run: cargo llvm-cov report --summary-only
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: llvm-cov-report
          path: lcov.info
          if-no-files-found: error
